# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui-folder/calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(720, 416)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui-folder/../icon/air-force.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color:#164863")
        Form.setWindowOpacity(0.98)
     
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(120, 120, 481, 171))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_1 = QtWidgets.QLabel(self.widget)
        self.label_1.setStyleSheet("QLabel {\n""color:#E5E1DA\n""}")
        self.label_1.setObjectName("label_1")
        self.horizontalLayout.addWidget(self.label_1)
        self.num1 = QtWidgets.QLineEdit(self.widget)
        self.num1.setObjectName("num1")
        self.horizontalLayout.addWidget(self.num1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setStyleSheet("QLabel {\n""color:#E5E1DA\n""}")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.num2 = QtWidgets.QLineEdit(self.widget)
        self.num2.setObjectName("num2")
        self.horizontalLayout_2.addWidget(self.num2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setStyleSheet("QLabel {\n""color:#E5E1DA\n""}")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.result = QtWidgets.QLineEdit(self.widget)
        self.result.setText("")
        self.result.setObjectName("result")
        self.horizontalLayout_4.addWidget(self.result)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.add = QtWidgets.QPushButton(self.widget)
        self.add.setStyleSheet("QLabel {\n""color:#E5E1DA\n""}")
        self.add.setObjectName("add")
        self.verticalLayout.addWidget(self.add)
        
        self.add.clicked.connect(self.addition)
        
        self.subtract = QtWidgets.QPushButton(self.widget)
        self.subtract.setStyleSheet("QLabel {\n""color:#E5E1DA\n""}")
        self.subtract.setObjectName("subtract")
        self.verticalLayout.addWidget(self.subtract)
        
        self.subtract.clicked.connect(self.subtraction)
        
        self.multiply = QtWidgets.QPushButton(self.widget)
        self.multiply.setStyleSheet("QLabel {\n""color:#E5E1DA\n""}")
        self.multiply.setObjectName("multiply")
        self.verticalLayout.addWidget(self.multiply)
        
        self.multiply.clicked.connect(self.multiplicaiton)
        
        self.divide = QtWidgets.QPushButton(self.widget)
        self.divide.setStyleSheet("QLabel {\n""color:#E5E1DA\n""}")
        self.divide.setObjectName("divide")
        self.verticalLayout.addWidget(self.divide)
        
        self.divide.clicked.connect(self.division)
        
        self.horizontalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
    def addition(self):
            num1 = self.num1.text()
            num2 = self.num2.text()
            
            if num1.isdigit() and num2.isdigit():
                addition = str(int(num1) + int(num2))
                self.result.setText(addition)
            else:
                self.result.setText("Invalid parameters!")
                    

    def subtraction(self):
            num1 = self.num1.text()
            num2 = self.num2.text()
            if num1.isdigit() and num2.isdigit():
                subtraction = str(int(num1) - int(num2))
                self.result.setText(subtraction)
            else:
                self.result.setText("Invalid parameters!")
            
    def multiplicaiton(self):
            num1 = self.num1.text()
            num2 = self.num2.text()
            if num1.isdigit() and num2.isdigit():
                multiplicaiton = str(int(num1) * int(num2))
                self.result.setText(multiplicaiton)
            else:
                self.result.setText("Invalid parameters!")
            
    def division(self):
            num1 = self.num1.text()
            num2 = self.num2.text()
            if num1.isdigit() and num2.isdigit():
                division = str(int(num1) / int(num2))
                self.result.setText(division)     
            else:
                self.result.setText("Invalid parameters!")       
             

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Calculator"))
        self.label_1.setText(_translate("Form", "First Number:"))
        self.label_2.setText(_translate("Form", "Second Number:"))
        self.label_3.setText(_translate("Form", "Result:"))
        self.add.setText(_translate("Form", "+"))
        self.subtract.setText(_translate("Form", "-"))
        self.multiply.setText(_translate("Form", "*"))
        self.divide.setText(_translate("Form", "/"))
        



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
